### PR TITLE
React native 0.72.1 and above metro.config.js

### PR DESCRIPTION
**Pull request by adsalihac**
Created issue
https://github.com/kristerkari/react-native-svg-transformer/issues/276

react-native to 0.72.1
@react-native/metro-config to ^0.72.7

### CODE REVIEW

**Comment by RominHalltari** [comment]
I am actually trying this approach and I get the following error: 
image

**Comment by kristerkari** [comment]
Thanks! I haven't tried out 0.72 yet, but I'll try to do that as soon as possible.

**Comment by adsalihac** [comment]
run `react-native start --reset-cache`

**Comment by adsalihac** [comment]
> I am actually trying this approach and I get the following error: image

run `react-native start --reset-cache`

react-native to 0.72.1
@react-native/metro-config to ^0.72.7

**Pull request merged**
