### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eduluq**
.svgrrc file should be placed in your assets directory

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks!

The `.svgrrc` file can also be in the project root, so why should the readme say this?

**Comment by eduluq** [comment]
Hey! 

It didn't work for me in the root directory. 

After checking out the code I found this line of code 

```
var config = resolveConfig.sync(resolveConfigDir(filename));
```

and when moving the .svgrrc to the assets folder it finally worked.

**Comment by kristerkari** [comment]
It should work in both root directory and asset directory, that's why there is the line that you pasted that tries to resolved the directory.

I was playing around the with the config file a couple of days ago, and it was working just fine for me in the project root directory.

**Comment by kristerkari** [comment]
Thanks @eduluq, I appreciate the PR, but I've also verified that the `.svgrrc` file works in the root directory, so I'll close this PR.

**Pull request closed without merging**
